version: '2'
services:
    web:
        image: php:7.0-apache
        volumes:
            - "./:/var/www/html"
        ports:
            - "9611:80"
        networks:
        - frontend
    pinghost:
        image: debian
        networks:
          - frontend
        links:
          - db
        command: ping -d  web
    db:
        image: mariadb
        networks:
          - frontend
        ports:
            - "9612:3306"
        volumes:
          - ./:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: netlab
          MYSQL_USER: root
          MYSQL_PASSWORD: netlab
          MYSQL_DATABASE: bigdata
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
          - frontend
        ports:
            - "9613:80"
        links:
           - db
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: netlab
    
networks:
    frontend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1
