version: '3.2' 
services:
    web1:
       build:
            context: ./Dockerfileweb
            dockerfile: ./Dockerfileweb/Dockerfile
       #deploy:
        #replicas: 2  
       image: 127.0.0.1:5000/prjweb
       volumes:
            - "./php/:/var/www/html"
       ports:
            - "9811:80"   
    web2:
       build:
            context: ./Dockerfileweb
            dockerfile: ./Dockerfileweb/Dockerfile
       image: 127.0.0.1:5000/prjweb
       volumes:
            - "./php/:/var/www/html"
       ports:
            - "9816:80"
    loadblancer:
       build: 
            context: ./Dockerfile
            dockerfile: ./Dockerfile/Dockerfile 
       image: 127.0.0.1:5000/prjnginx 
       ports:
            - "9812:80"
    db:
       build: 
            context: ./Dockerfiledb
            dockerfile: ./Dockerfilefdb/Dockerfile 
       image: 127.0.0.1:5000/prjdb
       ports:
            - "9813:3306"
    phpmyadmin:   
       build: 
            context: ./Dockerfilephpmyadmin
            dockerfile: ./Dockerfilephpmyadmin/Dockerfile
       image: 127.0.0.1:5000/prjphpmyadmin
       ports:
            - "9814:80"
       links:
            - db
